site_name: Ubiquitous Factory
site_description: Blog and Documentation for Smart Edge Systems using 
site_url: https://ubiqfac.tech

theme:
  name: material
  features:
    - navigation.indexes
  logo: assets/logo.png
  palette:
    primary: white
plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - brog
        - article
        - coras
        - quadit
        - amrite
        - announcement
      # authors_profiles: true
      pagination_per_page: 5
      # archive_pagination_per_page: 10
      # categories_pagination_per_page: 10
      # post_slugify: !!python/object/apply:ext.slugs.slugify
      #   kwds:
      #     short: true
  - meta
  - tags
  # - rss:
  #     match_path: "blog/posts/.*"
  #     date_from_meta:
  #       as_creation: date.created
  #       as_update: date.updated

# extra:
#   # social:
#   #   - icon: fontawesome/brands/linkedin
#   #     name: Mehal on Mastodon
#   #     link: https://www.linkedin.com/company/mehal-technologies

# hooks:
#   - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Overviews:
      - overviews/architecture.md
      - overviews/why-bootc.md
  - How Tos:
      - howto/index.md
      - howto/coras-getting-started.md
  - Blog:
     - blog/index.md
     - blog/tags.md